{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"main_colab.ipynb","provenance":[],"collapsed_sections":[],"mount_file_id":"1oDeXvQnruKddDaiy28S8g0YnOv44Yv0W","authorship_tag":"ABX9TyNTJO+PY8nUPlHjpv+xKfFn"},"kernelspec":{"name":"python3","display_name":"Python 3"},"accelerator":"GPU"},"cells":[{"cell_type":"code","metadata":{"id":"8m5pvk9nCdrj","colab_type":"code","colab":{}},"source":["#Comando para definir pasta\n","%cd drive/My\\ Drive/Labic\\ Segmentation/girino_segmentation/"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"N6XFcu-7Cijz","colab_type":"code","colab":{}},"source":["pip install tensorflow==1.15"],"execution_count":0,"outputs":[]},{"cell_type":"code","metadata":{"id":"IjS9LgHhCiIh","colab_type":"code","outputId":"90c75246-51d9-4b6c-f056-05093d3da8e4","executionInfo":{"status":"ok","timestamp":1585833970034,"user_tz":180,"elapsed":114745,"user":{"displayName":"Mauro Sergio","photoUrl":"https://lh3.googleusercontent.com/a-/AOh14GhRCuHz6KQzl4AkavizYSLvyGoMqpjebSeLT-shwg=s64","userId":"15795227297267185463"}},"colab":{"base_uri":"https://localhost:8080/","height":819}},"source":["#Comando para rodar o Python\n","!python main.py"],"execution_count":8,"outputs":[{"output_type":"stream","text":["2000/2000 [==============================] - 124s 62ms/step - loss: 0.0716 - dice_coef: 0.9284\n","WARNING:tensorflow:From new_main.py:70: The name tf.InteractiveSession is deprecated. Please use tf.compat.v1.InteractiveSession instead.\n","\n","2020-04-02 13:26:05.490453: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-02 13:26:05.490913: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: \n","name: Tesla P100-PCIE-16GB major: 6 minor: 0 memoryClockRate(GHz): 1.3285\n","pciBusID: 0000:00:04.0\n","2020-04-02 13:26:05.490986: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0\n","2020-04-02 13:26:05.491008: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0\n","2020-04-02 13:26:05.491025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0\n","2020-04-02 13:26:05.491046: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0\n","2020-04-02 13:26:05.491065: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0\n","2020-04-02 13:26:05.491083: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0\n","2020-04-02 13:26:05.491102: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7\n","2020-04-02 13:26:05.491187: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-02 13:26:05.491636: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-02 13:26:05.492006: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0\n","2020-04-02 13:26:05.492058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:\n","2020-04-02 13:26:05.492072: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 \n","2020-04-02 13:26:05.492081: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N \n","2020-04-02 13:26:05.492174: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-02 13:26:05.492619: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:983] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n","2020-04-02 13:26:05.493001: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15216 MB memory) -> physical GPU (device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0)\n","Traceback (most recent call last):\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py\", line 528, in _apply_op_helper\n","    preferred_dtype=default_dtype)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py\", line 1273, in internal_convert_to_tensor\n","    (dtype.name, value.dtype.name, value))\n","ValueError: Tensor conversion requested dtype float64 for Tensor with dtype uint8: <tf.Tensor 'Reshape_1:0' shape=(409600,) dtype=uint8>\n","\n","During handling of the above exception, another exception occurred:\n","\n","Traceback (most recent call last):\n","  File \"new_main.py\", line 71, in <module>\n","    _dice = (dice_coef(predicao, masks).eval())\n","  File \"/content/drive/My Drive/Labic Segmentation/girino_segmentation/unet.py\", line 11, in dice_coef\n","    intersection = K.sum(y_true_f * y_pred_f)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_ops.py\", line 899, in binary_op_wrapper\n","    return func(x, y, name=name)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/math_ops.py\", line 1206, in _mul_dispatch\n","    return gen_math_ops.mul(x, y, name=name)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_math_ops.py\", line 6701, in mul\n","    \"Mul\", x=x, y=y, name=name)\n","  File \"/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py\", line 564, in _apply_op_helper\n","    inferred_from[input_arg.type_attr]))\n","TypeError: Input 'y' of 'Mul' Op has type uint8 that does not match type float64 of argument 'x'.\n"],"name":"stdout"}]}]}